### ISSUE TITLE
Add existing scripts

### ISSUE THREAD

**Issue by hugolpz** [hugolpz/WeSpeaxExos#4]
Hello folks, could you add your existing "data to exos" python (?) script to this repositories.

@NehaDShakya @Zamanax : you added the exercices but your python code for Hindi and Japanese is not committed to github. Please find a way to share those as well within this repository. Right now, the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) is bad and is a critical weakness point for this project. 
@AmrMohamed226, thank for sharing your code, all good. cc @Sarveshmeenwa 

### Motivation
1. Finally gather back all done work
2. Tackle the [Bus factor risk](https://en.wikipedia.org/wiki/Bus_factor)

## Todo
- [x] AmrMohamed226 → Arabic Egyptian https://github.com/hugolpz/WeSpeaxExos/commit/b75655f5ef15f2966a24f7c8b3ef5f21f5829932
- [x] @NehaDShakya → English https://github.com/hugolpz/WeSpeaxExos/commit/264e732721f68038ad7020d808328a910a27d809
  - [ ] @Zamanax  → English 
- [x] @NehaDShakya → Hindi https://github.com/hugolpz/WeSpeaxExos/commit/4e6fa5282d0d8f951a3af16480f277e52f697c0c
- [x] Sarvesh  (no data)
- [ ] @Zamanax → Japanese
- [ ] Matthieu → French
- [ ] Matthieu → Chinese
